### ISSUE TITLE
attempting to enable module generates error

### ISSUE THREAD

**Issue by knowledges33ker** [ElusiveMind/user_entities#1]
Fatal error: Can't use function return value in write context in sites/all/modules/user_entities/user_entities.module on line124

**Comment by ElusiveMind** [comment]
Can you grab the dev version and see if this bug is fixed and there are no others. There were some conflicts with github's version vs drupal.org and I want to make sure I merged it right.

**Comment by knowledges33ker** [comment]
slightly different error now: 
Parse error: syntax error, unexpected T_IF in sites/all/modules/user_entities/user_entities.module on line 122

**Comment by ElusiveMind** [comment]
Ok — I’ll check this out more in a bit. About to leave for the drive home.

—
Namaste,
Michael R. Bagnall
Software Engineer, Architect, PHP & Drupal Ninja, Mastermind of Custom, Creative Solutions, Hockey Hack

Email: mrbagnall@icloud.com
Phone: (615) 476-3269
Twitter: @mbagnall17
Website: http://www.michaelbagnall.com


On June 12, 2015 at 2:44:34 PM, knowledges33ker (notifications@github.com) wrote:

slightly different error now:
Parse error: syntax error, unexpected T_IF in sites/all/modules/user_entities/user_entities.module on line 122

**Comment by ElusiveMind** [comment]
@knowledges33ker -- I have corrected these errors and tested out a few other problems. This has been released as version 1.3

**Comment by knowledges33ker** [comment]
Still getting an error when I try to install version 1.3:

Fatal error: Can't use function return value in write context in sites/all/modules/user_entities/user_entities.module on line 504

**Comment by ElusiveMind** [comment]
@knowledges33ker  -- This is undetected by me as I am running a later version of PHP that does not throw this error. I will correct and have you download a dev build to make sure it is fixed before releasing a new version.
